### PR TITLE
Add module configs for grove port / m5tack-env-iv sensor

### PR DESCRIPTION
**Pull request by jesserockz**
After taking control of the device configuration, you can add extra packages to add functionality without having to manage the entire configuration yourself

```yaml
substitutions:
  name: home-assistant-voice-090333
  friendly_name: Home Assistant Voice 090333
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml

  grove-i2c: github://esphome/home-assistant-voice-pe/modules/grove-i2c.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

```

### CODE REVIEW

**Comment by youkorr** [comment]
Hi everyone it would be interesting if you can implement it on esp32s3box3

**Review by balloob — DISMISSED** [review]

**Comment by jesserockz** [comment]
https://shop.m5stack.com/products/env-iv-unit-with-temperature-humidity-air-pressure-sensor-sht40-bmp280

- Temperature
- Humidity
- Atmospheric Pressure

Requires grove-i2c
```yaml
packages:
  grove-i2c: github://esphome/home-assistant-voice-pe/modules/grove-i2c.yaml
```

```yaml
sensor:
  - platform: sht4x
    i2c_id: grove_i2c
    temperature:
      name: Temperature
    humidity:
      name: Humidity

  - platform: bmp280_i2c
    i2c_id: grove_i2c
    address: 0x76
    pressure:
      name: Pressure
```

**Comment by jesserockz** [comment]
https://shop.m5stack.com/products/pir-module

- PIR Motion

Requires grove-power
```yaml
packages:
  grove-power: github://esphome/home-assistant-voice-pe/modules/grove-power.yaml

```

```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: 2
    name: Motion
    device_class: motion
```

**Comment by jesserockz** [comment]
https://shop.m5stack.com/products/tvoc-eco2-gas-unit-sgp30

- TVOC
- eCO2

Requires grove-i2c
```yaml
packages:
  grove-i2c: github://esphome/home-assistant-voice-pe/modules/grove-i2c.yaml
```

```yaml
sensor
  - platform: sgp30
    i2c_id: grove_i2c
    tvoc:
      name: "TVOC"
    eco2:
      name: "eCO2"
```

**Comment by jesserockz** [comment]
https://shop.m5stack.com/products/dlight-unit-ambient-light-sensor-bh1750fvi-tr

- Ambient Light

Requires grove-i2c
```yaml
packages:
  grove-i2c: github://esphome/home-assistant-voice-pe/modules/grove-i2c.yaml
```

```yaml
sensor:
  - platform: bh1750
    i2c_id: grove_i2c
    name: "Light Intensity"
```

**Review by balloob — APPROVED** [review]

**Pull request merged**
